# intially stolen from https://github.com/buildpacks/samples/blob/main/.github/workflows/build-and-deploy.yml

name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  repository_dispatch:
    types:
      - pack-release

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          docker version
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: "${{ github.repository_owner }}"
          password: ${{ secrets.GHRC_TOKEN }}
      - name: Determine download URL for latest pack
        id: pack-download-url
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            return github.repos.getLatestRelease({
                owner: "buildpacks",
                repo: "pack"
            }).then(result => {
                return result.data.assets
                  .filter(a => a.name.includes("linux"))
                  .map(a => a.browser_download_url)[0];
            })
      - name: Install pack
        run: |
          curl -s -L -o pack.tgz ${{ steps.pack-download-url.outputs.result }}
          tar -xvf pack.tgz
      - name: Build
        run: ./pack build "ghcr.io/${{ github.repository }}:${{ github.sha }}" --builder gcr.io/buildpacks/builder:v1
      # for whatever reason "--publish" does not notify that the upload was a success
      - name: Publish
        run: docker push "ghcr.io/${{ github.repository }}:${{ github.sha }}"
